### ISSUE TITLE
wrong ages

### ISSUE THREAD

**Issue by guillaumecabanel** [nfilzi/lewagon-sql-lectures#1]
in https://github.com/nfilzi/lewagon-sql_day_1_lecture_boilerplate/blob/master/population_statistics/support/raw_data/inhabitants.csv

:trollface:

**Comment by nfilzi** [comment]
I'm welcoming any PRs fixing the ages, you :trollface:

**Comment by nfilzi** [comment]
UP @guillaumecabanel :p

**Comment by nfilzi** [comment]
Fixes needed here, if you're willing → https://github.com/nfilzi/lewagon-sql-lectures/blob/master/population_statistics/support/sql/seeds.sql

**Comment by nfilzi** [comment]
Closing this @guillaumecabanel. You'll eternally be 32 for students @ Le Wagon 😁
